### ISSUE TITLE
Output C headers for embedded SW

### ISSUE THREAD

**Issue by aignacio** [rggen/rggen#104]
Hey @taichi-ishitani,

thanks for this project, it's really impressive the framework. Quick question, are you looking to implement C headers generation as an output? Nothing fancy but something that SW engineers could simply include to start design drivers, like
```c
#define REGISTER_FILE_0_BASE_ADDR  0x00000000
#define REGISTER_FILE_0_BIT_0_MASK 0x00000001
....
```

**Comment by aignacio** [comment]
@taichi-ishitani,

hmm, I understand the issue you're explaining. Maybe you could add an optional register parameter like `c_fmt` which would allow either 32 or 64 bits option to format every register into chunks of 32/64 for C header generation, this way it is up to the user to align the bitfields to match its intention. In case the parameter is **set** and the user configures wrongly the optional parameter `c_fmt` by making registers wider an error can be thrown explaining the mismatch. I think this error is not a problem because usually when you access the CSRs through a CPU it is either word-aligned or d-word aligned and the AXI txn will match this size of the registers. In my opinion, I don't see any practical reason why we could have a CSR with a width bigger than 32/64b for instance as the main usage of the CSRs are to configure the accelerator to run some task, also enabling 32b / 64b options you cover almost all CPUs in the earth =). 

Something like this for instance:

**Input cfg**
```yml
register:
- name: reg_0
  offset_address: 0x00
  c_fmt: 32
  bit_fields:
  - { name: field_0, bit_assignment: { width: 1,   lsb:  0 }, type: rw, initial_value: 0 }
  - { name: field_1, bit_assignment: { width: 1,   lsb:  1}, type: rw, initial_value: 0 }
  - { name: field_2, bit_assignment: { width: 4,   lsb:  3}, type: rw, initial_value: 0 } 
```

**Output C header**
```c
#define REG_0_BASE_ADDR        0x0000 // 32-bit fmt, for 64-bit 0xXXXX_XXXX
#define REG_0_FIELD_0_OFFSET   0x0
#define REG_0_FIELD_0_MASK     0x1
#define REG_0_FIELD_1_OFFSET   0x1
#define REG_0_FIELD_1_MASK     0x1
#define REG_0_FIELD_2_OFFSET   0x3
#define REG_0_FIELD_2_MASK     0xF
```
That's just a suggestion if you think it's irrelevant or that doesn't work it's fine, but having something like that would make it even greater IMO. =)
