### ISSUE TITLE
Constants and expressions support

### ISSUE THREAD

**Issue by m-kru** [rggen/rggen#149]
Does RgGen support constants and expressions? For example, I would like to define two module constants `X` and `Y`, and then I would like to calculate different values utilizing these constants in the expressions.

**Comment by taichi-ishitani** [comment]
Can you tell me more details?
I'd like to know register map snippet which you want to write.

**Comment by m-kru** [comment]
Pseudo description:
```yaml
register_blocks:
  - constants: {X: 1, Y: 2}
  - name: block_0
    byte_size: 256
    registers:
    - name: register_0
      bit_fields:
      - { name: bit_field_0, bit_assignment: { width: 4 }, type: rw  , initial_value: X ** Y }

```
