### ISSUE TITLE
Allow to specify configuration parameters on register map files

### ISSUE THREAD

**Issue by taichi-ishitani** [rggen/rggen#221]
Allow to specify `bus_width` and `protocol` configuration parameters on register map files.
For example:

```yaml
register_blocks:
  - name: block_0
    byte_size: 256
    bus_width: 64
    protocol: axi4lite
```
