### ISSUE TITLE
Initialize non sequential bit field register block

### ISSUE THREAD

**Issue by alejandro-castro-ortegon** [rggen/rggen#241]
**Is your feature request related to a problem? Please describe.**

Currently, there's no way to initialize a non sequential bit field register block. For example, consider the following register:

```
register_blocks:
  - name: my_regs 
    comment: "ABC"
    byte_size: 64
    registers:
    - name: non_seq_reg
      comment: "reg"
      size: [8, step: 4]
      offset_address: 0x00
      bit_fields:
      - { name: non_zero_data,    bit_assignment: { lsb:   0, width: 32 }, type: rw, initial_value: 0x0, comment: "My data" }
```

**Describe the solution you'd like**

It would be nice to have a way to initialize every bit of the non sequential bit field register block, something like `initial_value: [0x111111, 0x22222222, 0x3, 0x44444444, 0x11111111, 0x22, 0x333333333, 0x4444]`

refs: rggen/rggen#240
