### ISSUE TITLE
Replace codeclimate with qlty

### ISSUE THREAD

**Issue by taichi-ishitani** [rggen/rggen#247]
https://qlty.sh

**Comment by taichi-ishitani** [comment]
How to convert Codelimate's `fetch` setting.

```toml
[[plugin.fetch]]
url = "https://raw.githubusercontent.com/rggen/rggen-devtools/master/config/rubocop_common.yml"
path = "rubocop_common.yml"
```
