### ISSUE TITLE
Omit name of bit field when its parent register has only one bit field

### ISSUE THREAD

**Issue by taichi-ishitani** [rggen/rggen#3]
If a register has one bit field only, name of the bit filed should be able to be omitted.
In this case, use name of its parent register as its name. 
That is, following register specification can be accepted and name of bit field will be set to `foo`.

```yaml
name: foo
offset_address: 0x00
bit_fields:
    - { bit_assignment: { lsb: 0, width: 1}, type: rw, initial_value: 0 }
```
