### ISSUE TITLE
Enhance YAML/JSON based register map

### ISSUE THREAD

**Issue by taichi-ishitani** [rggen/rggen#36]
Currently, one layer is described by using one Hash and an Array at the special key is used to describe a set of sub layers.

```yaml
register_maps:
  - name: foo_0
    registers:
    - name: bar_0
    - name: baz_0
    register_files:
    - name: bar_1
    - name: baz_1
```

This notation has a problem; Describing sub-layers in order `bar_0 -> bar_1 -> baz_0 -> baz_1` like below

```yaml
register_maps:
  - name: foo_0
    registers:
    - name: bar_0
    register_files:
    - name: bar_1
    registers:
    - name: baz_0
    register_files:
    - name: baz_1
```

does not work well because `bar_0` and `bar_1` are overridden by `baz_0` and `baz_1`.

To resolve this problem, new notation using an Array of Hash will be introduce like below.

```yaml
- register_block:
  - name: foo_0
  - register:
    - name: bar_0
  - register_file:
    - name: bar_1
  - register:
    - name: baz_0
  - register_file:
    - name: baz_1
```

An Array will be merged into one Hash except for values having special keys `register_block`/`register_file`/`register`/`bit_field`.
These values will be pushed into an Array at special keys `register_blocks`/`register_files`/`registers`/`bit_fields`.

After loading the new notation, following Hash object will be getten.

```ruby
{
  register_blocks: [
    {
      name: foo_0,
      registers: [
        { name: bar_0 },
        { name: baz_0 }
      ],
      register_files: [
        { name: bar_1 },
        { name: baz_1 }
      ]
    }
  ]
}
```
