### ISSUE TITLE
No error is reported even though step is less than width

### ISSUE THREAD

**Issue by taichi-ishitani** [rggen/rggen#75]
**Describe the bug**
No error is reported even though `step` is less than `width`.

**To Reproduce**

```yaml
- register_block:
  - name: foo
    byte_size: 256
  - register:
    - name: bar
      bit_fields:
      - { name: baz, bit_assignment: { width: 2, sequence_size: 2, step: 1 }, type: rw, initial_value: 0 }
```

Load this register map.

**Expected behavior**

`step` should be equal to or grater than `width` to avoid overlapping each elements.
 Therefore, an error should be reported if `step` is less than `width`.
