### ISSUE TITLE
Add internal register type

### ISSUE THREAD

**Issue by taichi-ishitani** [rggen/rggen#80]
Add `internal` register type to support nested register block.
This type is to specify a register block which is put within other register block.

Outline of register map format:

```yaml
register_blocks:
  - name: inner_block_0
    byte_size: 128
    # regsiter descriptions

  - name: inner_block_1
    byte_size: 128
    # regsiter descriptions

  - name: top_block
    byte_size: 256
    regsiters:
      - { name inner_block_0, type: [internal, inner_block_0] }
      - { name inner_block_1, type: [internal, inner_block_1] }
```

Reason why nested register block support is added as a new register type:

* similar to external register type
* no change to precondition of register map structure
