### ISSUE TITLE
Order of registers within generated files is wrong

### ISSUE THREAD

**Issue by taichi-ishitani** [rggen/rggen#94]
**Describe the bug**

Order of registers within generated files are wrong.

**To Reproduce**

Give the YAML file below and generate source files.

```yaml
- register_block:
  - name: test
    byte_size:  256

  - register:
    - name: foo
      offset_address: 0x00
      bit_fields:
      - { name: foo, bit_assignment: { width: 1 }, type: ro }

  - register_file:
    - name: bar
      offset_address: 0x04
      register:
      - name: bar
        offset_address: 0x00
        bit_fields:
        - { name: bar, bit_assignment: { width: 1 }, type: ro }

  - register:
    - name: baz
      offset_address: 0x08
      bit_fields:
      - { name: baz, bit_assignment: { width: 1 }, type: ro }
```

source files with wrong order of registers will be generated. For example:

```markdown
## test

* byte_size
    * 256

|name|offset_address|
|:--|:--|
|[foo](#test-foo)|0x00|
|[baz](#test-baz)|0x08|
|[bar.bar](#test-bar-bar)|0x04|
```

**Expected behavior**

The order should be:

* foo
* bar.bar
* baz
